import { Task, UserProfile, AppSettings, Category, DailyPlanItem, CalendarEvent, WallpaperPreset } from '../types';

export const WALLPAPER_PRESETS: WallpaperPreset[] = [
  {
    id: 'twilight-heart-moon',
    name: 'Twilight Heart & Crescent Moon',
    tagline: 'Dreamy pastel purple twilight sky with heart cloud & crescent moon',
    url: '/images/twilight-heart-cloud.jpg',
    thumbnail: '/images/twilight-heart-cloud.jpg',
    accentColor: '#8b5cf6',
  },
  {
    id: 'roses-bouquet',
    name: 'Red Rose Bouquet',
    tagline: 'Lush romantic bouquet of fresh crimson roses',
    url: '/images/rose-bouquet.jpg',
    thumbnail: '/images/rose-bouquet.jpg',
    accentColor: '#7c3aed',
  },
  {
    id: 'cosmos-meadow',
    name: 'Cosmos Blossom Meadow',
    tagline: 'Vibrant wildflowers bloom in open nature meadow',
    url: '/images/cosmos-meadow.jpg',
    thumbnail: '/images/cosmos-meadow.jpg',
    accentColor: '#6366f1',
  },
  {
    id: 'sunset-dusk',
    name: 'Golden Sunset Bicycles',
    tagline: 'Warm evening sunset silhouette & serene skies',
    url: '/images/sunset-bicycle.jpg',
    thumbnail: '/images/sunset-bicycle.jpg',
    accentColor: '#0ea5e9',
  },
  {
    id: 'floating-petals',
    name: 'Heart Petal Breeze',
    tagline: 'Dreamy floating petals against airy horizon',
    url: '/images/heart-petals.jpg',
    thumbnail: '/images/heart-petals.jpg',
    accentColor: '#8b5cf6',
  },
  {
    id: 'soft-minimal',
    name: 'Soft Lavender & Cloud Glass',
    tagline: 'Gentle pastel lavender and cream watercolor aesthetic',
    url: '',
    thumbnail: '/images/twilight-heart-cloud.jpg',
    accentColor: '#8b5cf6',
  },
];

export const CATEGORIES: { name: Category; color: string; bg: string; border: string; text: string; dot: string; image: string }[] = [
  { name: 'Machine Learning', color: 'violet', bg: 'bg-violet-50', border: 'border-violet-200', text: 'text-violet-700', dot: 'bg-violet-500', image: '/images/twilight-heart-cloud.jpg' },
  { name: 'Python', color: 'sky', bg: 'bg-sky-50', border: 'border-sky-200', text: 'text-sky-700', dot: 'bg-sky-500', image: '/images/cosmos-meadow.jpg' },
  { name: 'Data Analytics', color: 'indigo', bg: 'bg-indigo-50', border: 'border-indigo-200', text: 'text-indigo-700', dot: 'bg-indigo-500', image: '/images/sunset-bicycle.jpg' },
  { name: 'Internship', color: 'purple', bg: 'bg-purple-50', border: 'border-purple-200', text: 'text-purple-700', dot: 'bg-purple-500', image: '/images/rose-bouquet.jpg' },
  { name: 'Aptitude', color: 'emerald', bg: 'bg-emerald-50', border: 'border-emerald-200', text: 'text-emerald-700', dot: 'bg-emerald-500', image: '/images/cosmos-meadow.jpg' },
  { name: 'GATE', color: 'violet', bg: 'bg-violet-50', border: 'border-violet-200', text: 'text-violet-700', dot: 'bg-violet-500', image: '/images/twilight-heart-cloud.jpg' },
  { name: 'Academics', color: 'blue', bg: 'bg-blue-50', border: 'border-blue-200', text: 'text-blue-700', dot: 'bg-blue-500', image: '/images/heart-petals.jpg' },
  { name: 'Non-Academics', color: 'amber', bg: 'bg-amber-50', border: 'border-amber-200', text: 'text-amber-700', dot: 'bg-amber-500', image: '/images/sunset-bicycle.jpg' },
  { name: 'Personal', color: 'teal', bg: 'bg-teal-50', border: 'border-teal-200', text: 'text-teal-700', dot: 'bg-teal-500', image: '/images/cosmos-meadow.jpg' },
  { name: 'Other', color: 'slate', bg: 'bg-slate-50', border: 'border-slate-200', text: 'text-slate-700', dot: 'bg-slate-500', image: '/images/twilight-heart-cloud.jpg' },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'ML — GeeksforGeeks',
    category: 'Machine Learning',
    priority: 'high',
    status: 'active',
    estimatedMinutes: 60,
    createdAt: new Date().toISOString(),
    completionHistory: [
      { id: 'c-1', date: new Date(Date.now() - 86400000 * 1).toISOString().split('T')[0], timestamp: new Date(Date.now() - 86400000 * 1).toISOString(), actualMinutes: 60, estimatedMinutes: 60, notes: 'Completed Decision Tree algorithms' },
      { id: 'c-2', date: new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0], timestamp: new Date(Date.now() - 86400000 * 3).toISOString(), actualMinutes: 55, estimatedMinutes: 60, notes: 'Feature scaling and cross-validation' },
    ],
    notes: 'Module 3: Decision Trees, Random Forests, and Gradient Boosting algorithms with code practice.',
    recurrence: 'daily',
    order: 1,
  },
  {
    id: 'task-2',
    title: 'Python — YouTube',
    category: 'Python',
    priority: 'medium',
    status: 'active',
    estimatedMinutes: 45,
    createdAt: new Date().toISOString(),
    completionHistory: [
      { id: 'c-3', date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0], timestamp: new Date(Date.now() - 86400000 * 2).toISOString(), actualMinutes: 45, estimatedMinutes: 45, notes: 'Decorators and generator expressions' },
    ],
    notes: 'Advanced OOP concepts, generators, decorators, and multi-threading practice video tutorials.',
    recurrence: 'daily',
    order: 2,
  },
  {
    id: 'task-3',
    title: 'ML — Pendrive',
    category: 'Machine Learning',
    priority: 'high',
    status: 'active',
    estimatedMinutes: 90,
    createdAt: new Date().toISOString(),
    completionHistory: [
      { id: 'c-4', date: new Date(Date.now() - 86400000 * 4).toISOString().split('T')[0], timestamp: new Date(Date.now() - 86400000 * 4).toISOString(), actualMinutes: 90, estimatedMinutes: 90, notes: 'Linear Algebra and Calculus for ML' },
    ],
    notes: 'Offline video lectures on Neural Networks, Backpropagation, and Mathematics for ML.',
    recurrence: 'daily',
    order: 3,
  },
  {
    id: 'task-4',
    title: 'Meeting — Internship',
    category: 'Internship',
    priority: 'high',
    status: 'active',
    estimatedMinutes: 30,
    createdAt: new Date().toISOString(),
    completionHistory: [
      { id: 'c-5', date: new Date(Date.now() - 86400000 * 1).toISOString().split('T')[0], timestamp: new Date(Date.now() - 86400000 * 1).toISOString(), actualMinutes: 30, estimatedMinutes: 30, notes: 'Sprint planning and milestone check' },
    ],
    notes: 'Daily standup meeting with team lead, sprint review, and project milestone deliverables.',
    deadline: new Date(Date.now() + 86400000 * 1).toISOString().split('T')[0],
    recurrence: 'weekdays',
    order: 4,
  },
  {
    id: 'task-5',
    title: 'Aptitude',
    category: 'Aptitude',
    priority: 'medium',
    status: 'active',
    estimatedMinutes: 30,
    createdAt: new Date().toISOString(),
    completionHistory: [
      { id: 'c-6', date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0], timestamp: new Date(Date.now() - 86400000 * 2).toISOString(), actualMinutes: 30, estimatedMinutes: 30, notes: 'Permutations & Combinations speed drill' },
    ],
    notes: 'Quantitative aptitude, speed math, logical reasoning, and data interpretation practice set.',
    recurrence: 'daily',
    order: 5,
  },
  {
    id: 'task-6',
    title: 'GATE',
    category: 'GATE',
    priority: 'high',
    status: 'active',
    estimatedMinutes: 60,
    createdAt: new Date().toISOString(),
    completionHistory: [
      { id: 'c-7', date: new Date(Date.now() - 86400000 * 1).toISOString().split('T')[0], timestamp: new Date(Date.now() - 86400000 * 1).toISOString(), actualMinutes: 65, estimatedMinutes: 60, notes: 'Graph Theory & Dijkstra proof' },
      { id: 'c-8', date: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0], timestamp: new Date(Date.now() - 86400000 * 5).toISOString(), actualMinutes: 60, estimatedMinutes: 60, notes: 'Dynamic Programming previous year questions' },
    ],
    notes: 'Algorithms & Data Structures: Dynamic Programming, Graph Theory, and previous year question solve.',
    deadline: new Date(Date.now() + 86400000 * 45).toISOString().split('T')[0],
    recurrence: 'daily',
    order: 6,
  },
  {
    id: 'task-7',
    title: 'Non-Academics — NEOPAT',
    category: 'Non-Academics',
    priority: 'medium',
    status: 'active',
    estimatedMinutes: 45,
    createdAt: new Date().toISOString(),
    completionHistory: [],
    notes: 'College online portal assessment and coding tests practice.',
    recurrence: 'weekly',
    order: 7,
  },
  {
    id: 'task-8',
    title: 'Non-Academics — Offline assignments & records',
    category: 'Non-Academics',
    priority: 'low',
    status: 'active',
    estimatedMinutes: 60,
    createdAt: new Date().toISOString(),
    completionHistory: [],
    notes: 'Complete laboratory observation write-ups, semester record submissions, and diagrams.',
    recurrence: 'weekly',
    order: 8,
  },
  {
    id: 'task-9',
    title: 'Machine Learning Fundamentals — Videos in Deep Learning app',
    category: 'Machine Learning',
    priority: 'high',
    status: 'active',
    estimatedMinutes: 45,
    createdAt: new Date().toISOString(),
    completionHistory: [
      { id: 'c-9', date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0], timestamp: new Date(Date.now() - 86400000 * 2).toISOString(), actualMinutes: 45, estimatedMinutes: 45, notes: 'CNN convolutional layers and max pooling' },
    ],
    notes: 'Deep learning course modules, CNN architecture, convolutional filters, and pooling layers.',
    recurrence: 'daily',
    order: 9,
  },
  {
    id: 'task-10',
    title: 'AI FOR ALL GLOBAL INTERNSHIP',
    category: 'Internship',
    priority: 'high',
    status: 'active',
    estimatedMinutes: 90,
    createdAt: new Date().toISOString(),
    completionHistory: [
      { id: 'c-10', date: new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0], timestamp: new Date(Date.now() - 86400000 * 3).toISOString(), actualMinutes: 90, estimatedMinutes: 90, notes: 'Model validation metrics and confusion matrix' },
    ],
    notes: 'Implement computer vision pipeline & classification model evaluation for internship capstone.',
    deadline: new Date(Date.now() + 86400000 * 5).toISOString().split('T')[0],
    recurrence: 'daily',
    order: 10,
  },
];

export const INITIAL_PROFILE: UserProfile = {
  name: 'Janith Sai',
  title: 'Aspiring Machine Learning Engineer & Data Analyst',
  bio: 'Dedicated learner focused on mastering Machine Learning, Data Analytics, cracking GATE, and securing top-tier AI roles.',
  academicYear: 'Final Year B.Tech — Computer Science & Engineering',
  focusAreas: [
    'Machine Learning',
    'Data Analytics',
    'GATE Preparation',
    'AI Internships',
    'Campus Placements',
  ],
  goals: [
    'Become a top-tier ML Engineer',
    'Master advanced Data Analytics & SQL / Tableau pipelines',
    'Prepare rigorously for GATE CSE',
    'Build end-to-end full stack AI projects',
    'Successfully complete AI For All Global Internship',
  ],
  avatarUrl: '/images/twilight-heart-cloud.jpg',
  streak: {
    current: 5,
    longest: 14,
    lastActiveDate: new Date().toISOString().split('T')[0],
  },
};

export const DEFAULT_PASSKEY_HASH = 'a60395727931f6e2467fef2958315579f187a052ff37c8ee8efd32b535cb5e58';

export const INITIAL_SETTINGS: AppSettings = {
  theme: 'light',
  wallpaper: 'twilight-heart-moon',
  wallpaperOverlay: 0.80,
  enableFloatingPetals: false, // Turned off red petals, cute star sparkles enabled
  enableCuteStars: true,
  defaultDuration: 45,
  defaultPriority: 'high',
  passkeyHash: DEFAULT_PASSKEY_HASH,
  soundEnabled: true,
  ambientSound: 'bell',
  notificationsEnabled: false,
  dailyTargetMinutes: 240,
};

export const MOTIVATIONAL_QUOTES = [
  "Small progress every day becomes a big achievement.",
  "Focus on the task in front of you.",
  "Consistency beats intensity.",
  "One completed task is better than ten planned tasks.",
  "Discipline is choosing between what you want now and what you want most.",
  "Your future is created by what you do today, not tomorrow.",
  "Deep focus is the superpower of the 21st century.",
  "Every hour invested in GATE and Machine Learning builds your dream career.",
];

export const INITIAL_TODAY_PLAN: DailyPlanItem[] = [
  { id: 'plan-1', time: '09:00', title: 'Meeting — Internship', category: 'Internship', durationMinutes: 30, isCompleted: false },
  { id: 'plan-2', time: '10:30', title: 'ML — GeeksforGeeks', category: 'Machine Learning', durationMinutes: 60, isCompleted: false },
  { id: 'plan-3', time: '14:00', title: 'Python — YouTube', category: 'Python', durationMinutes: 45, isCompleted: false },
  { id: 'plan-4', time: '18:00', title: 'GATE', category: 'GATE', durationMinutes: 60, isCompleted: false },
  { id: 'plan-5', time: '20:30', title: 'Aptitude Practice', category: 'Aptitude', durationMinutes: 30, isCompleted: false },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'cal-1',
    title: 'Internship Standup Meeting',
    date: new Date().toISOString().split('T')[0],
    time: '09:00',
    durationMinutes: 30,
    category: 'Internship',
    isCompleted: false,
    type: 'meeting',
  },
  {
    id: 'cal-2',
    title: 'GATE Algorithms Practice',
    date: new Date().toISOString().split('T')[0],
    time: '18:00',
    durationMinutes: 60,
    category: 'GATE',
    isCompleted: false,
    type: 'study',
  },
  {
    id: 'cal-3',
    title: 'AI Global Capstone Deadline',
    date: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
    time: '23:59',
    durationMinutes: 0,
    category: 'Internship',
    isCompleted: false,
    type: 'deadline',
  },
];
